// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNx8NMdeFuuKC6Bn29fIRXtRDXC278Vg8',
    appId: '1:614838442164:web:ef93a646e02f77ac915fe1',
    messagingSenderId: '614838442164',
    projectId: 'cucumberproj',
    authDomain: 'cucumberproj.firebaseapp.com',
    storageBucket: 'cucumberproj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtc8StOlpIo9uv3IHrMIyebqL_9o91C-w',
    appId: '1:614838442164:android:8820ecb8a0d52d6f915fe1',
    messagingSenderId: '614838442164',
    projectId: 'cucumberproj',
    storageBucket: 'cucumberproj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP9J8YnASP-np7QQaKQqzSpVsNj-hFi6c',
    appId: '1:614838442164:ios:9a10c403222cfa73915fe1',
    messagingSenderId: '614838442164',
    projectId: 'cucumberproj',
    storageBucket: 'cucumberproj.firebasestorage.app',
    iosBundleId: 'com.example.dope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP9J8YnASP-np7QQaKQqzSpVsNj-hFi6c',
    appId: '1:614838442164:ios:9a10c403222cfa73915fe1',
    messagingSenderId: '614838442164',
    projectId: 'cucumberproj',
    storageBucket: 'cucumberproj.firebasestorage.app',
    iosBundleId: 'com.example.dope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNx8NMdeFuuKC6Bn29fIRXtRDXC278Vg8',
    appId: '1:614838442164:web:609ea5f27104e460915fe1',
    messagingSenderId: '614838442164',
    projectId: 'cucumberproj',
    authDomain: 'cucumberproj.firebaseapp.com',
    storageBucket: 'cucumberproj.firebasestorage.app',
  );
}
